### ISSUE TITLE
Programmatic?

### ISSUE THREAD

**Issue by simenandre** [negokaz/drawioex#1]
Hello 👋

Have you thought of adding programmatic access to this library? There are often use cases where you'd want to run through including. If you are thinking about doing it, maybe go the extra step of adding Typescript definitions (or just refactor to Typescript)?

**Comment by negokaz** [comment]
Hello cobraz.

I have no plan to do it. But I welcome contributions. Note that this library can't run easily on browser because it depends on puppeteer.
